services:
  - type: static_site
    name: lmsprojectfrontend
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    envVars:
      - key: VITE_API_URL
        value: https://lmsproject1-cuzs.onrender.com
    routes:
      - path: /*
        destination: /index.html
